services:
  - type: web
    name: taskflow
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_USER
        sync: false
      - key: BREVO_FROM
        sync: false
